#if defined _index_included
  #endinput
#endif

#define _index_included

#include <amxmodx>
#include <amxmisc>
#include <fakemeta>
#include <reapi>

// Globals
#include <competitive/compatibility>
#include <competitive/globals>
#include <competitive/cvars>
#include <competitive/utils>
#include <competitive/menutils>
#include <competitive/client>

// Modules
#include <competitive/votekick>
#include <competitive/votepause>
#include <competitive/captain>
#include <competitive/mute>
#include <competitive/roundinfo>
#include <competitive/autoready>
#include <competitive/autodmg>
#include <competitive/afkicker>
#include <competitive/stats>
#include <competitive/chooseteam>
#include <competitive/clrates>
#include <competitive/speckick>
#include <competitive/kniferound>

// Core
#include <competitive/pugmenu>
#include <competitive/cmd>
#include <competitive/event>
#include <competitive/hook>
#include <competitive/half>
